# Generated by Django 4.2.6 on 2023-10-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kyc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'verbose_name_plural': 'KYC'},
        ),
        migrations.AddField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
    ]
